"""Discover row structures by leave-one-out parallel-column corroboration."""
from __future__ import annotations

from dataclasses import dataclass
from decimal import Decimal

from . import labels, sums


MAX_HYPOTHESES_PER_BLOCK = 5000


@dataclass(frozen=True)
class Evaluation:
    column: int
    total_cell: dict
    run: sums.Run
    tied_runs: tuple[sums.Run, ...]
    # The span this run was cut from stepped over a section caption. The caption
    # is a heading inside the block rather than a boundary of it -- Apple's cash
    # flow statement sets "Adjustments to reconcile net income..." and "Changes
    # in operating assets and liabilities:" between the rows that make *Cash
    # generated by operating activities* -- but a span that crossed one was
    # decided by something other than the arithmetic, so it may confirm and may
    # never break. Same rule as `sums`, for the same reason.
    crossed_caption: bool = False
    # Fewer than two addends actually carry a figure -- "778 + dash = 778". Such
    # a column proves nothing on its own and may never establish or corroborate
    # a structure, but once two independent columns have established one it is
    # entitled to ride along: the evidence is the row structure the others
    # proved, not this column's own arithmetic. Withholding it leaves a row half
    # ticked, with the reviewer unable to tell a scan limit from a real gap.
    degenerate: bool = False

    @property
    def ties(self) -> bool:
        return bool(self.tied_runs)

    def tied_on(self, negated_indices: tuple[int, ...]) -> sums.Run | None:
        return next(
            (run for run in self.tied_runs if run.negated_indices == negated_indices),
            None,
        )


@dataclass(frozen=True)
class Structure:
    top: int
    total_row: int
    evaluations: tuple[Evaluation, ...]


def _evaluation(block, column: int, top: int, total_row: int) -> Evaluation | None:
    header = next((item for item in block.header_labels if item["columnIndex"] == column), None)
    if header and labels.is_non_additive_column(header.get("text", "")):
        return None
    total = block.cell(total_row, column)
    if total is None or sums.value_of(total) in (None, Decimal(0)):
        return None
    decimals = int(total.get("decimals", -1))
    rows = [row for row in range(top, total_row) if not block.is_caption_row(row)]
    crossed = len(rows) != total_row - top
    if crossed and (block.is_caption_row(top) or not rows):
        # A span starting on a caption is the span starting one row lower, and
        # counting it twice would inflate the hypothesis count for nothing.
        return None
    cells = [block.cell(row, column) for row in rows]
    if any(cell is None or sums.value_of(cell) is None or not sums._eligible(cell, decimals) for cell in cells):
        return None
    concrete = [cell for cell in cells if cell is not None]
    nonzero = sum(1 for cell in concrete if sums.value_of(cell) != 0)
    if len(concrete) < 2:
        return None
    run = sums.Run("leaves", tuple(concrete), sums.value_of(total), decimals)
    if sums.double_counts(run):
        return None
    return Evaluation(
        column,
        total,
        run,
        sums.tied_variants(run),
        crossed_caption=crossed,
        degenerate=nonzero < 2,
    )


def _proportional(first: Evaluation, second: Evaluation) -> bool:
    return sums.proportional_values(
        [sums.value_of(cell) or Decimal(0) for cell in first.run.cells],
        [sums.value_of(cell) or Decimal(0) for cell in second.run.cells],
    )


def _independent(evaluations: list[Evaluation]) -> list[Evaluation]:
    representatives: list[Evaluation] = []
    for evaluation in evaluations:
        if not any(_proportional(evaluation, prior) for prior in representatives):
            representatives.append(evaluation)
    return representatives


def discover(block) -> tuple[list[Structure], int]:
    """Return hypotheses retained by at least one exact, non-degenerate tie."""
    retained: list[Structure] = []
    tested = 0
    for total_row in range(2, block.row_count):
        for top in range(total_row - 2, -1, -1):
            if tested >= MAX_HYPOTHESES_PER_BLOCK:
                return retained, tested
            tested += 1
            evaluations = [
                evaluation
                for column in range(1, block.column_count)
                if (evaluation := _evaluation(block, column, top, total_row)) is not None
            ]
            if any(
                evaluation.ties
                for evaluation in evaluations
                if not evaluation.degenerate
            ):
                retained.append(Structure(top, total_row, tuple(evaluations)))
    return retained, tested


def resolve(block) -> tuple[list[dict], dict]:
    """Publish the strongest proven structure for each candidate total cell."""
    structures, tested = discover(block)
    established_columns = {
        evaluation.column
        for structure in structures
        for evaluation in structure.evaluations
        if not evaluation.degenerate
        for pattern in {
            run.negated_indices
            for item in structure.evaluations
            if not item.degenerate
            for run in item.tied_runs
        }
        if evaluation.tied_on(pattern) is not None
        and len(_independent([
            item
            for item in structure.evaluations
            if not item.degenerate and item.tied_on(pattern) is not None
        ])) >= 2
    }
    proposals: dict[str, list[tuple[tuple[int, int, int, int], dict]]] = {}
    for structure in structures:
        patterns = {
            run.negated_indices
            for evaluation in structure.evaluations
            if not evaluation.degenerate
            for run in evaluation.tied_runs
        }
        for pattern in patterns:
            tied = [
                evaluation
                for evaluation in structure.evaluations
                if not evaluation.degenerate
                and evaluation.tied_on(pattern) is not None
            ]
            agreeing = _independent(tied)
            agreeing_columns = {evaluation.column for evaluation in agreeing}
            for evaluation in structure.evaluations:
                own_label = labels.is_total_label(evaluation.total_cell.get("rowLabel", ""))
                own_tie = evaluation.tied_on(pattern)
                assessed = own_tie or evaluation.run.with_negated(pattern)
                other_agreement = len([column for column in agreeing_columns if column != evaluation.column])
                if evaluation.degenerate:
                    # Rides on a structure two independent columns established,
                    # and only ever to confirm. A degenerate column that misses
                    # says nothing, so it never speaks.
                    publish = own_tie is not None and len(agreeing) >= 2
                elif own_tie is not None:
                    publish = len(agreeing) >= 2 or (len(agreeing) >= 1 and own_label)
                else:
                    publish = other_agreement >= 2 or (
                        other_agreement >= 1
                        and (own_label or evaluation.column in established_columns)
                    )
                if own_tie is None and evaluation.crossed_caption:
                    # A caption is the statement separating one block from the
                    # next, so a span that stepped over one holds rows the
                    # arithmetic did not choose. An exact tie is still a tie; a
                    # miss says something about the scan, not about the page.
                    continue
                if not publish or (own_tie is None and not sums._plausible(assessed)):
                    continue
                signals = []
                if own_label:
                    label = evaluation.total_cell.get("rowLabel", "")
                    signals.append({"name": "label-total", "evidence": f'row label reads "{label}"'})
                if other_agreement:
                    columns = ", ".join(str(column) for column in sorted(agreeing_columns - {evaluation.column}))
                    signals.append({
                        "name": "column-corroboration",
                        "evidence": f"the same signed rows foot independently in column{'s' if other_agreement != 1 else ''} {columns}",
                    })
                if not signals:
                    continue
                outcome = "confirmed" if own_tie is not None else "break"
                payload = {
                    "cell": evaluation.total_cell,
                    "signals": signals,
                    "outcome": outcome,
                    "resolution": assessed.as_dict(),
                    "top": structure.top,
                }
                # The nearest exact relationship wins. Once sign reversal is
                # available, preferring the longest algebraic identity can hide
                # the statement's immediate subtotal relationship through
                # cancellation.
                score = (other_agreement, -len(pattern), -len(evaluation.run.cells), structure.top)
                proposals.setdefault(evaluation.total_cell["id"], []).append((score, payload))
    chosen = [max(candidates, key=lambda item: item[0])[1] for candidates in proposals.values()]
    chosen.extend(_resolve_subtotal_pairs(block, chosen))
    chosen.sort(key=lambda item: (item["cell"]["rowIndex"], item["cell"]["columnIndex"]))
    return chosen, {"hypotheses": tested, "retained": len(structures)}


def _resolve_subtotal_pairs(block, chosen: list[dict]) -> list[dict]:
    """Resolve totals built from sibling subtotals separated by their blocks.

    The value lattice deliberately splits at section captions. The detected
    grid preserves the full statement, but a contiguous row-span search still
    sees the components inside each subtotal. This pass walks only already
    corroborated subtotal rows and asks whether two sibling subtotals foot the
    immediately following row. Newly established rows participate in the next
    iteration, which builds Gross margin and then Operating income on the Apple
    statement without adding label vocabulary.
    """
    added: list[dict] = []
    emitted = {entry["cell"]["id"] for entry in chosen}
    while True:
        all_entries = chosen + added
        established_rows = sorted({
            int(entry["cell"]["rowIndex"])
            for entry in all_entries
            if entry["outcome"] == "confirmed"
            and any(signal["name"] == "column-corroboration" for signal in entry["signals"])
        })
        proposals: dict[str, list[tuple[tuple[int, int, int], dict]]] = {}
        for last in established_rows:
            total_row = last + 1
            if total_row >= block.row_count:
                continue
            for first in (row for row in established_rows if row < last):
                evaluations = [
                    evaluation
                    for column in range(1, block.column_count)
                    if (
                        evaluation := _sparse_evaluation(
                            block, column, (first, last), total_row
                        )
                    ) is not None
                ]
                patterns = {
                    run.negated_indices
                    for evaluation in evaluations
                    for run in evaluation.tied_runs
                }
                for pattern in patterns:
                    tied = [
                        evaluation for evaluation in evaluations
                        if evaluation.tied_on(pattern) is not None
                    ]
                    agreeing = _independent(tied)
                    if len(agreeing) < 2:
                        continue
                    agreeing_columns = {evaluation.column for evaluation in agreeing}
                    for evaluation in evaluations:
                        own_tie = evaluation.tied_on(pattern)
                        # A sparse pair proves only columns that tie. A sibling
                        # column may legitimately carry extra components not in
                        # this pair (Apple's marketable-securities table does),
                        # so a miss here is not evidence of a break.
                        if own_tie is None:
                            continue
                        assessed = own_tie
                        other_agreement = len(agreeing_columns - {evaluation.column})
                        signals = [{
                            "name": "column-corroboration",
                            "evidence": (
                                "the same signed subtotal rows foot independently "
                                f"in columns {', '.join(str(column) for column in sorted(agreeing_columns - {evaluation.column}))}"
                            ),
                        }]
                        if labels.is_total_label(evaluation.total_cell.get("rowLabel", "")):
                            label = evaluation.total_cell.get("rowLabel", "")
                            signals.insert(0, {
                                "name": "label-total",
                                "evidence": f'row label reads "{label}"',
                            })
                        top = min(
                            (
                                int(entry["top"])
                                for entry in all_entries
                                if entry["cell"]["columnIndex"] == evaluation.column
                                and entry["cell"]["rowIndex"] in (first, last)
                            ),
                            default=first,
                        )
                        payload = {
                            "cell": evaluation.total_cell,
                            "signals": signals,
                            "outcome": "confirmed",
                            "resolution": assessed.as_dict(),
                            "top": top,
                        }
                        score = (other_agreement, -len(pattern), first)
                        proposals.setdefault(evaluation.total_cell["id"], []).append((score, payload))
        iteration = [
            max(candidates, key=lambda item: item[0])[1]
            for cell_id, candidates in proposals.items()
            if cell_id not in emitted
        ]
        if not iteration:
            break
        added.extend(iteration)
        newly_confirmed = {
            entry["cell"]["id"] for entry in iteration if entry["outcome"] == "confirmed"
        }
        if not newly_confirmed:
            break
        emitted.update(entry["cell"]["id"] for entry in iteration)
    return added


def _sparse_evaluation(
    block, column: int, addend_rows: tuple[int, int], total_row: int
) -> Evaluation | None:
    header = next((item for item in block.header_labels if item["columnIndex"] == column), None)
    if header and labels.is_non_additive_column(header.get("text", "")):
        return None
    total = block.cell(total_row, column)
    cells = [block.cell(row, column) for row in addend_rows]
    if total is None or sums.value_of(total) in (None, Decimal(0)) or any(cell is None for cell in cells):
        return None
    decimals = int(total.get("decimals", -1))
    concrete = [cell for cell in cells if cell is not None]
    if any(sums.value_of(cell) is None or not sums._eligible(cell, decimals) for cell in concrete):
        return None
    run = sums.Run("subtotals", tuple(concrete), sums.value_of(total), decimals)
    return Evaluation(column, total, run, sums.tied_variants(run))
