"""Discover row structures by leave-one-out parallel-column corroboration."""
from __future__ import annotations

from dataclasses import dataclass
from decimal import Decimal

from engines.financial_table import labels

from . import nominate, sums


MAX_HYPOTHESES_PER_BLOCK = 5000


@dataclass(frozen=True)
class Evaluation:
    column: int
    total_cell: dict
    run: sums.Run
    tied_runs: tuple[sums.Run, ...]
    # The span this run was cut from stepped over a section caption. The caption
    # is a heading inside the block rather than a boundary of it -- Apple's cash
    # flow statement sets "Adjustments to reconcile net income..." and "Changes
    # in operating assets and liabilities:" between the rows that make *Cash
    # generated by operating activities* -- but a span that crossed one was
    # decided by something other than the arithmetic, so it may confirm and may
    # never break. Same rule as `sums`, for the same reason.
    crossed_caption: bool = False
    # Fewer than two addends actually carry a figure -- "778 + dash = 778". Such
    # a column proves nothing on its own and may never establish or corroborate
    # a structure, but once two independent columns have established one it is
    # entitled to ride along: the evidence is the row structure the others
    # proved, not this column's own arithmetic. Withholding it leaves a row half
    # ticked, with the reviewer unable to tell a scan limit from a real gap.
    degenerate: bool = False

    @property
    def ties(self) -> bool:
        return bool(self.tied_runs)

    def tied_on(self, negated_indices: tuple[int, ...]) -> sums.Run | None:
        # A dash or numeric zero has no sign.  Two columns still describe the
        # same signed row structure when a reversed suffix contains a zero in
        # one of them, so compare only the indices that contribute a value in
        # this column.  The published run follows the same canonical form.
        effective = tuple(
            index
            for index in negated_indices
            if sums.value_of(self.run.cells[index]) != 0
        )
        return next(
            (run for run in self.tied_runs if run.negated_indices == effective),
            None,
        )

    def with_pattern(self, negated_indices: tuple[int, ...]) -> sums.Run:
        effective = tuple(
            index
            for index in negated_indices
            if sums.value_of(self.run.cells[index]) != 0
        )
        return self.run.with_negated(effective)


@dataclass(frozen=True)
class Structure:
    top: int
    total_row: int
    evaluations: tuple[Evaluation, ...]


def _evaluation(block, column: int, top: int, total_row: int) -> Evaluation | None:
    header = next((item for item in block.header_labels if item["columnIndex"] == column), None)
    if header and labels.is_non_additive_column(header.get("text", "")):
        return None
    total = block.cell(total_row, column)
    if total is None or sums.value_of(total) in (None, Decimal(0)):
        return None
    decimals = int(total.get("decimals", -1))
    rows = [row for row in range(top, total_row) if not block.is_caption_row(row)]
    crossed = len(rows) != total_row - top
    if crossed and (block.is_caption_row(top) or not rows):
        # A span starting on a caption is the span starting one row lower, and
        # counting it twice would inflate the hypothesis count for nothing.
        return None
    cells = [block.cell(row, column) for row in rows]
    if any(cell is None or sums.value_of(cell) is None or not sums._eligible(cell, decimals) for cell in cells):
        return None
    concrete = [cell for cell in cells if cell is not None]
    nonzero = sum(1 for cell in concrete if sums.value_of(cell) != 0)
    if len(concrete) < 2:
        return None
    run = sums.Run("leaves", tuple(concrete), sums.value_of(total), decimals)
    if sums.double_counts(run):
        return None
    return Evaluation(
        column,
        total,
        run,
        sums.tied_variants(run),
        crossed_caption=crossed,
        degenerate=nonzero < 2,
    )


def _proportional(first: Evaluation, second: Evaluation) -> bool:
    return sums.proportional_values(
        [sums.value_of(cell) or Decimal(0) for cell in first.run.cells],
        [sums.value_of(cell) or Decimal(0) for cell in second.run.cells],
    )


def _independent(evaluations: list[Evaluation]) -> list[Evaluation]:
    representatives: list[Evaluation] = []
    for evaluation in evaluations:
        if not any(_proportional(evaluation, prior) for prior in representatives):
            representatives.append(evaluation)
    return representatives


def _independent_witnesses(
    evaluation: Evaluation, tied: list[Evaluation]
) -> list[Evaluation]:
    """Tying columns that independently corroborate this particular column.

    Independence is relative to the column being judged.  Computing one set of
    representatives for the whole table lets a proportional column borrow the
    representative it was collapsed into and call that independent evidence.
    Putting the judged column first, then discarding its representative, makes
    that impossible while still collapsing witnesses proportional to each
    other.
    """
    representatives = _independent(
        [evaluation] + [item for item in tied if item.column != evaluation.column]
    )
    return [item for item in representatives if item.column != evaluation.column]


def discover(block) -> tuple[list[Structure], int]:
    """Return hypotheses retained by at least one exact, non-degenerate tie.

    Short spans are visited across the whole block before longer ones.  The
    safety cap therefore reduces maximum look-back evenly instead of silently
    making the bottom of a long table unreachable after the upper rows consume
    the entire budget.
    """
    retained: list[Structure] = []
    tested = 0
    for span_length in range(2, block.row_count):
        for total_row in range(span_length, block.row_count):
            if tested >= MAX_HYPOTHESES_PER_BLOCK:
                return retained, tested
            tested += 1
            top = total_row - span_length
            evaluations = [
                evaluation
                for column in range(1, block.column_count)
                if (evaluation := _evaluation(block, column, top, total_row)) is not None
            ]
            if any(
                evaluation.ties
                for evaluation in evaluations
                if not evaluation.degenerate
            ):
                retained.append(Structure(top, total_row, tuple(evaluations)))
    return retained, tested


def resolve(block) -> tuple[list[dict], dict]:
    """Publish the strongest proven structure for each candidate total cell."""
    structures, tested = discover(block)
    proposals: dict[str, list[tuple[tuple[bool, int, int, int, int], dict]]] = {}
    for structure in structures:
        patterns = {
            run.negated_indices
            for evaluation in structure.evaluations
            if not evaluation.degenerate
            for run in evaluation.tied_runs
        }
        for pattern in patterns:
            tied = [
                evaluation
                for evaluation in structure.evaluations
                if not evaluation.degenerate
                and evaluation.tied_on(pattern) is not None
            ]
            agreeing = _independent(tied)
            for evaluation in structure.evaluations:
                own_label = labels.is_total_label(evaluation.total_cell.get("rowLabel", ""))
                own_tie = evaluation.tied_on(pattern)
                assessed = own_tie or evaluation.with_pattern(pattern)
                witnesses = (
                    _independent_witnesses(evaluation, tied)
                    if own_tie is not None
                    else _independent(tied)
                )
                witness_columns = {item.column for item in witnesses}
                other_agreement = len(witnesses)
                if evaluation.degenerate:
                    # Rides on a structure two independent columns established,
                    # and only ever to confirm. A degenerate column that misses
                    # says nothing, so it never speaks.
                    publish = own_tie is not None and len(agreeing) >= 2
                elif own_tie is not None:
                    # The structure route contributes only when another
                    # non-proportional column corroborates this one. A labelled
                    # run of three or more remains independently admissible,
                    # but a two-addend coincidence must not bypass the label
                    # route's explicit floor.
                    publish = other_agreement >= 1 or (
                        own_label
                        and len(evaluation.run.cells)
                        >= nominate.MIN_ADDENDS_ON_ONE_SIGNAL
                    )
                else:
                    publish = other_agreement >= 2 or (
                        other_agreement >= 1
                        and own_label
                    )
                if own_tie is None and evaluation.crossed_caption:
                    # A caption is the statement separating one block from the
                    # next, so a span that stepped over one holds rows the
                    # arithmetic did not choose. An exact tie is still a tie; a
                    # miss says something about the scan, not about the page.
                    continue
                if not publish or (own_tie is None and not sums._plausible(assessed)):
                    continue
                signals = []
                if own_label:
                    label = evaluation.total_cell.get("rowLabel", "")
                    signals.append({"name": "label-total", "evidence": f'row label reads "{label}"'})
                if other_agreement:
                    columns = ", ".join(str(column) for column in sorted(witness_columns))
                    signals.append({
                        "name": "column-corroboration",
                        "evidence": f"the same signed rows foot independently in column{'s' if other_agreement != 1 else ''} {columns}",
                    })
                if not signals:
                    continue
                outcome = "confirmed" if own_tie is not None else "break"
                payload = {
                    "cell": evaluation.total_cell,
                    "signals": signals,
                    "outcome": outcome,
                    "resolution": assessed.as_dict(),
                    "top": structure.top,
                }
                # The nearest exact relationship wins. Once sign reversal is
                # available, preferring the longest algebraic identity can hide
                # the statement's immediate subtotal relationship through
                # cancellation.
                # A break means no permitted run ties.  If another retained
                # structure for this same cell does tie, publishing the miss
                # would contradict that definition however many columns support
                # the alternative.  Exact resolutions therefore rank first;
                # evidence strength and the nearest relationship break ties.
                score = (
                    outcome == "confirmed",
                    other_agreement,
                    -len(pattern),
                    -len(evaluation.run.cells),
                    structure.top,
                )
                proposals.setdefault(evaluation.total_cell["id"], []).append((score, payload))
    chosen = _choose_non_overlapping_proposals(block, proposals)
    chosen.extend(_resolve_subtotal_pairs(block, chosen))
    chosen.sort(key=lambda item: (item["cell"]["rowIndex"], item["cell"]["columnIndex"]))
    possible = max(0, (block.row_count - 1) * (block.row_count - 2) // 2)
    return chosen, {
        "hypotheses": tested,
        "retained": len(structures),
        "truncated": tested < possible,
    }


def _choose_non_overlapping_proposals(block, proposals: dict) -> list[dict]:
    """Choose totals top-down without counting part of a known subtotal twice.

    `sums.double_counts` catches the arithmetic form when every constituent is
    inside the candidate.  A candidate may start halfway through the block,
    however, and then the partial constituents no longer add to the subtotal.
    The established structure supplies the missing geometric fact: taking any
    row from a subtotal's owned interval alongside that subtotal still counts
    part of the block twice.

    Totals are chosen in row order so only already-finalized subtotals constrain
    a parent.  Filtering candidates before ranking also preserves a valid
    alternative for the same cell instead of dropping the cell wholesale when
    its initially strongest candidate overlaps.
    """
    established: dict[tuple[int, int], int] = {}
    chosen: list[dict] = []
    ordered = sorted(
        proposals.values(),
        key=lambda candidates: (
            int(candidates[0][1]["cell"]["rowIndex"]),
            int(candidates[0][1]["cell"]["columnIndex"]),
        ),
    )
    for candidates in ordered:
        valid = []
        for score, entry in candidates:
            column = int(entry["cell"]["columnIndex"])
            rows = {
                int(block.by_id[cell_id]["rowIndex"])
                for cell_id in entry["resolution"]["addendCellIds"]
                if cell_id in block.by_id
            }
            overlaps = any(
                subtotal_row in rows
                and any(top <= row < subtotal_row for row in rows)
                for (subtotal_column, subtotal_row), top in established.items()
                if subtotal_column == column
            )
            if not overlaps:
                valid.append((score, entry))
        if not valid:
            continue
        selected = max(valid, key=lambda item: item[0])[1]
        column = int(selected["cell"]["columnIndex"])
        rows = {
            int(block.by_id[cell_id]["rowIndex"])
            for cell_id in selected["resolution"]["addendCellIds"]
            if cell_id in block.by_id
        }
        # A subtotal built from another subtotal owns the deepest interval it
        # consumed, not merely the visible rows in its immediate equation. The
        # parent walk must resume above that whole interval or it will add part
        # of the nested subtotal a second time. Disney's property-and-equipment
        # total is 33,152 + projects + land; 33,152 itself owns attractions less
        # depreciation, so the 41,255 block begins at attractions, not 33,152.
        selected["top"] = min(
            [int(selected["top"])]
            + [
                top
                for (subtotal_column, subtotal_row), top in established.items()
                if subtotal_column == column and subtotal_row in rows
            ]
        )
        chosen.append(selected)
        if selected["outcome"] == "confirmed":
            established[
                (
                    column,
                    int(selected["cell"]["rowIndex"]),
                )
            ] = int(selected["top"])
    return chosen


def _resolve_subtotal_pairs(block, chosen: list[dict]) -> list[dict]:
    """Resolve totals built from sibling subtotals separated by their blocks.

    The value lattice deliberately splits at section captions. The detected
    grid preserves the full statement, but a contiguous row-span search still
    sees the components inside each subtotal. This pass walks only already
    corroborated subtotal rows and asks whether two sibling subtotals foot the
    immediately following row. Newly established rows participate in the next
    iteration, which builds Gross margin and then Operating income on the Apple
    statement without adding label vocabulary.
    """
    added: list[dict] = []
    emitted = {entry["cell"]["id"] for entry in chosen}
    while True:
        all_entries = chosen + added
        established_rows = sorted({
            int(entry["cell"]["rowIndex"])
            for entry in all_entries
            if entry["outcome"] == "confirmed"
            and any(signal["name"] == "column-corroboration" for signal in entry["signals"])
        })
        proposals: dict[str, list[tuple[tuple[int, int, int], dict]]] = {}
        for last in established_rows:
            total_row = last + 1
            if total_row >= block.row_count:
                continue
            for first in (row for row in established_rows if row < last):
                evaluations = [
                    evaluation
                    for column in range(1, block.column_count)
                    if (
                        evaluation := _sparse_evaluation(
                            block, column, (first, last), total_row
                        )
                    ) is not None
                ]
                patterns = {
                    run.negated_indices
                    for evaluation in evaluations
                    for run in evaluation.tied_runs
                }
                for pattern in patterns:
                    tied = [
                        evaluation for evaluation in evaluations
                        if evaluation.tied_on(pattern) is not None
                    ]
                    agreeing = _independent(tied)
                    if len(agreeing) < 2:
                        continue
                    agreeing_columns = {evaluation.column for evaluation in agreeing}
                    for evaluation in evaluations:
                        own_tie = evaluation.tied_on(pattern)
                        # A sparse pair proves only columns that tie. A sibling
                        # column may legitimately carry extra components not in
                        # this pair (Apple's marketable-securities table does),
                        # so a miss here is not evidence of a break.
                        if own_tie is None:
                            continue
                        assessed = own_tie
                        other_agreement = len(agreeing_columns - {evaluation.column})
                        signals = [{
                            "name": "column-corroboration",
                            "evidence": (
                                "the same signed subtotal rows foot independently "
                                f"in columns {', '.join(str(column) for column in sorted(agreeing_columns - {evaluation.column}))}"
                            ),
                        }]
                        if labels.is_total_label(evaluation.total_cell.get("rowLabel", "")):
                            label = evaluation.total_cell.get("rowLabel", "")
                            signals.insert(0, {
                                "name": "label-total",
                                "evidence": f'row label reads "{label}"',
                            })
                        top = min(
                            (
                                int(entry["top"])
                                for entry in all_entries
                                if entry["cell"]["columnIndex"] == evaluation.column
                                and entry["cell"]["rowIndex"] in (first, last)
                            ),
                            default=first,
                        )
                        payload = {
                            "cell": evaluation.total_cell,
                            "signals": signals,
                            "outcome": "confirmed",
                            "resolution": assessed.as_dict(),
                            "top": top,
                        }
                        score = (other_agreement, -len(pattern), first)
                        proposals.setdefault(evaluation.total_cell["id"], []).append((score, payload))
        iteration = [
            max(candidates, key=lambda item: item[0])[1]
            for cell_id, candidates in proposals.items()
            if cell_id not in emitted
        ]
        if not iteration:
            break
        added.extend(iteration)
        newly_confirmed = {
            entry["cell"]["id"] for entry in iteration if entry["outcome"] == "confirmed"
        }
        if not newly_confirmed:
            break
        emitted.update(entry["cell"]["id"] for entry in iteration)
    return added


def _sparse_evaluation(
    block, column: int, addend_rows: tuple[int, int], total_row: int
) -> Evaluation | None:
    header = next((item for item in block.header_labels if item["columnIndex"] == column), None)
    if header and labels.is_non_additive_column(header.get("text", "")):
        return None
    total = block.cell(total_row, column)
    cells = [block.cell(row, column) for row in addend_rows]
    if total is None or sums.value_of(total) in (None, Decimal(0)) or any(cell is None for cell in cells):
        return None
    decimals = int(total.get("decimals", -1))
    concrete = [cell for cell in cells if cell is not None]
    if any(sums.value_of(cell) is None or not sums._eligible(cell, decimals) for cell in concrete):
        return None
    run = sums.Run("subtotals", tuple(concrete), sums.value_of(total), decimals)
    return Evaluation(column, total, run, sums.tied_variants(run))
