// Generated by scripts/generate_reconcile_review.mjs. Do not edit.
export interface ReviewBounds {
  x: number;
  y: number;
  width: number;
  height: number;
}

export interface ReviewCell {
  id: string;
  pageIndex: number;
  bounds: ReviewBounds;
  text: string;
  label: string;
  column: string;
  value: string;
  dash: boolean;
  origin: "scan" | "manual";
}

export interface ReviewTerm {
  cellId: string;
  coefficient: -1 | 1;
}

export interface ReviewEvaluation {
  state: "exact-match" | "difference" | "not-evaluable";
  sum: string;
  delta: string;
  reason: string;
}

export interface ReviewEquation {
  id: string;
  regionId: string;
  targetId: string;
  terms: Array<ReviewTerm>;
  axis: "vertical" | "cross" | "manual";
  origin: "detected" | "manual";
  decision: "unreviewed" | "accepted" | "rejected" | "deferred";
  evaluation: ReviewEvaluation;
  issue: "open" | "explained" | "resolved";
  note: string;
  signature: string;
}

export interface ReviewRegion {
  id: string;
  pageIndex: number;
  bounds: ReviewBounds;
  label: string;
}

export interface ReviewCorrection {
  cellId: string;
  value: string;
  reason: string;
}

export interface ReviewRevision {
  revision: number;
  at: string;
  equations: Array<ReviewEquation>;
  corrections: Array<ReviewCorrection>;
  evidence: Array<ReviewCell>;
  reviewedPages: Array<number>;
}

export interface ReviewArchive {
  scanId: string;
  geometryFingerprint: string;
  revision: number;
  evidence: Array<ReviewCell>;
  regions: Array<ReviewRegion>;
  equations: Array<ReviewEquation>;
  corrections: Array<ReviewCorrection>;
  history: Array<ReviewRevision>;
  reviewedPages: Array<number>;
}

export interface ReviewWorkspace {
  version: 1;
  documentId: string;
  scanId: string;
  geometryFingerprint: string;
  pageCount: number;
  revision: number;
  evidence: Array<ReviewCell>;
  regions: Array<ReviewRegion>;
  equations: Array<ReviewEquation>;
  corrections: Array<ReviewCorrection>;
  history: Array<ReviewRevision>;
  archives: Array<ReviewArchive>;
  reviewedPages: Array<number>;
}

export interface ReviewDraft {
  regionId: string;
  targetId: string;
  terms: Array<ReviewTerm>;
  axis: "vertical" | "cross" | "manual";
}

export interface ReviewOperation {
  kind: "equation" | "decision" | "correction" | "value" | "issue" | "restore" | "page";
  equationId?: string;
  equation?: ReviewDraft;
  equationIds?: Array<string>;
  decision?: "unreviewed" | "accepted" | "rejected" | "deferred";
  correction?: ReviewCorrection;
  cell?: ReviewCell;
  issue?: "open" | "explained" | "resolved";
  note?: string;
  revision?: number;
  pageIndex?: number;
  reviewed?: boolean;
}

export interface ReviewRequest {
  type: "reconcile-review-request";
  version: 1;
  requestId: string;
  pdfId: string;
  mode: "load" | "preview" | "commit" | "save-workbook";
  scanId: string;
  expectedRevision: number;
  operations: Array<ReviewOperation>;
}

export interface ReviewResponse {
  type: "reconcile-review-response";
  version: 1;
  requestId: string;
  pdfId: string;
  status: "loaded" | "preview" | "updated" | "workbook-saved" | "error";
  workspace?: ReviewWorkspace;
  evaluation?: ReviewEvaluation;
  error?: string;
}

export interface ReviewWorkerJob {
  job_id: string;
  command: "reconcile-review";
  request: ReviewRequest;
  model_base64: string;
  values_base64: string;
  review_base64: string;
}

export interface ReviewWorkerResult {
  job_id: string;
  status: "success";
  response: ReviewResponse;
  review_base64: string;
}

