#Requires -Version 5.1
<#
  Writes Properties\GeneratedVersion.cs with the given version string.
  Called by the GenerateVersionFile MSBuild target before CoreCompile.
  For normal builds the version is "dev"; installer builds pass the real version.
#>
param(
    [Parameter(Mandatory)][string]$Version,
    [Parameter(Mandatory)][ValidateSet("true", "false")][string]$Beta,
    [Parameter(Mandatory)][string]$OutputPath
)

$isDevelopment = if ($Version -eq "dev") { "true" } else { "false" }
$isBeta = $Beta.ToLowerInvariant()

$content = @"
// Auto-generated by the build — do not edit manually.
namespace Talliark.Addin
{
    internal static class AppVersion
    {
        public const string Current = "$Version";
        public static readonly bool IsDevelopment = $isDevelopment;
        public static readonly bool IsBeta = $isBeta;
    }
}
"@

Set-Content -Path $OutputPath -Value $content -Encoding UTF8
