#Requires -Version 5.1
<#
  Writes Properties\GeneratedVersion.cs with the version and compile-time settings.
  Called by the GenerateVersionFile MSBuild target before CoreCompile. For normal
  builds the version is "dev"; installer builds pass the real version. Local
  settings come from the repository .env and are never copied beside the add-in.
#>
param(
    [Parameter(Mandatory)][string]$Version,
    [Parameter(Mandatory)][ValidateSet("true", "false")][string]$Beta,
    [Parameter(Mandatory)][string]$OutputPath,
    [Parameter(Mandatory)][string]$EnvPath
)

$isDevelopment = if ($Version -eq "dev") { "true" } else { "false" }
$isBeta = $Beta.ToLowerInvariant()

# Build-time settings belong in the generated assembly, not beside the installed
# add-in. This keeps the local .env useful during development without shipping it.
$bugReportEmail = ""
if (Test-Path -LiteralPath $EnvPath) {
    foreach ($line in Get-Content -LiteralPath $EnvPath) {
        if ($line -notmatch '^\s*BUG_REPORT_EMAIL\s*=\s*(.*)$') { continue }

        $bugReportEmail = $Matches[1].Trim()
        if (($bugReportEmail.StartsWith('"') -and $bugReportEmail.EndsWith('"')) -or
            ($bugReportEmail.StartsWith("'") -and $bugReportEmail.EndsWith("'"))) {
            $bugReportEmail = $bugReportEmail.Substring(1, $bugReportEmail.Length - 2)
        }
        break
    }
}

if ($bugReportEmail) {
    try {
        $parsedAddress = New-Object System.Net.Mail.MailAddress($bugReportEmail)
        if ($parsedAddress.Address -ne $bugReportEmail) {
            throw "BUG_REPORT_EMAIL must contain one plain email address."
        }
    }
    catch {
        throw "BUG_REPORT_EMAIL in '$EnvPath' is not a valid email address."
    }
}
else {
    if ($isDevelopment -eq "true") {
        Write-Warning "BUG_REPORT_EMAIL is not set in '$EnvPath'. The bug-report button will explain that it is not configured."
    }
    else {
        throw "BUG_REPORT_EMAIL must be set in '$EnvPath' before creating a release build."
    }
}

function ConvertTo-CSharpString([string]$value) {
    return $value.Replace('\', '\\').Replace('"', '\"')
}

$escapedVersion = ConvertTo-CSharpString $Version
$escapedBugReportEmail = ConvertTo-CSharpString $bugReportEmail

$content = @"
// Auto-generated by the build — do not edit manually.
namespace Talliark.Addin
{
    internal static class AppVersion
    {
        public const string Current = "$escapedVersion";
        public static readonly bool IsDevelopment = $isDevelopment;
        public static readonly bool IsBeta = $isBeta;
    }

    internal static class BuildConfiguration
    {
        public const string BugReportEmail = "$escapedBugReportEmail";
    }
}
"@

Set-Content -Path $OutputPath -Value $content -Encoding UTF8
