// Deterministic bindings for the assisted-review contract; no runtime shape copies.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { resolve, dirname } from "node:path";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const contract = JSON.parse(readFileSync(resolve(root, "contracts/reconcile-review-v1.json"), "utf8"));
const literal = JSON.stringify;
function tsType(schema) {
  if (schema.$ref) return schema.$ref.split("/").at(-1);
  if ("const" in schema) return literal(schema.const);
  if (schema.enum) return schema.enum.map(literal).join(" | ");
  if (schema.type === "array") return `Array<${tsType(schema.items)}>`;
  return { string: "string", boolean: "boolean", integer: "number", number: "number" }[schema.type]
    ?? (() => { throw new Error(`Unsupported binding shape: ${literal(schema)}`); })();
}
function csType(schema, optional = false) {
  if (schema.$ref) return schema.$ref.split("/").at(-1);
  if (schema.type === "array") return `List<${csType(schema.items)}>`;
  const type = { string: "string", boolean: "bool", integer: "int", number: "double" }[schema.type];
  // Constants have no type keyword in JSON Schema.
  const result = "const" in schema ? (typeof schema.const === "number" ? "int" : "string") : type;
  if (!result) throw new Error(`Unsupported C# type: ${literal(schema)}`);
  return optional && result !== "string" ? result + "?" : result;
}
function pyType(schema) {
  if (schema.$ref) return schema.$ref.split("/").at(-1);
  if ("const" in schema) return `Literal[${literal(schema.const)}]`;
  if (schema.enum) return `Literal[${schema.enum.map(literal).join(", ")}]`;
  if (schema.type === "array") return `list[${pyType(schema.items)}]`;
  return { string: "str", boolean: "bool", integer: "int", number: "float" }[schema.type];
}
const ts = ["// Generated by scripts/generate_reconcile_review.mjs. Do not edit."];
const cs = ["// Generated by scripts/generate_reconcile_review.mjs. Do not edit.", "using System.Collections.Generic;", "namespace Talliark.Addin.Modules.CustomXml.Models", "{"];
const py = ['"""Generated assisted-review bindings. Do not edit."""', "from __future__ import annotations", "import json", "from typing import Literal, NotRequired, TypedDict", ""];
for (const [name, schema] of Object.entries(contract.definitions)) {
  ts.push(`export interface ${name} {`);
  cs.push(`    internal sealed class ${name}`, "    {");
  py.push(`class ${name}(TypedDict):`);
  for (const [key, field] of Object.entries(schema.properties)) {
    const optional = !schema.required.includes(key);
    ts.push(`  ${key}${optional ? "?" : ""}: ${tsType(field)};`);
    cs.push(`        public ${csType(field, optional)} ${key} { get; set; }`);
    py.push(`    ${key}: ${optional ? `NotRequired[${pyType(field)}]` : pyType(field)}`);
  }
  ts.push("}", ""); cs.push("    }"); py.push("");
}
cs.push("}");
py.push(`SCHEMA = json.loads(${literal(JSON.stringify(contract))})`, "");
const outputs = [
  ["src/web/apps/reconcile/src/types/reconcile-review.generated.ts", ts.join("\n") + "\n"],
  ["src/Talliark.Addin/Modules/CustomXml/Models/ReconcileReview.generated.cs", cs.join("\n") + "\n"],
  ["src/python/schemas/reconcile_review_generated.py", py.join("\n") + "\n"],
];
for (const [path, content] of outputs) {
  const target = resolve(root, path);
  if (process.argv.includes("--check")) {
    if (readFileSync(target, "utf8").replaceAll("\r\n", "\n") !== content) throw new Error(`Stale contract binding: ${path}`);
  } else writeFileSync(target, content);
}
