// Generated by scripts/generate_reconcile_review.mjs. Do not edit.
using System.Collections.Generic;
namespace Talliark.Addin.Modules.CustomXml.Models
{
    internal sealed class ReviewBounds
    {
        public double x { get; set; }
        public double y { get; set; }
        public double width { get; set; }
        public double height { get; set; }
    }
    internal sealed class ReviewCell
    {
        public string id { get; set; }
        public int pageIndex { get; set; }
        public ReviewBounds bounds { get; set; }
        public string text { get; set; }
        public string label { get; set; }
        public string column { get; set; }
        public string value { get; set; }
        public bool dash { get; set; }
        public string origin { get; set; }
    }
    internal sealed class ReviewTerm
    {
        public string cellId { get; set; }
        public int coefficient { get; set; }
    }
    internal sealed class ReviewEvaluation
    {
        public string state { get; set; }
        public string sum { get; set; }
        public string delta { get; set; }
        public string reason { get; set; }
    }
    internal sealed class ReviewEquation
    {
        public string id { get; set; }
        public string regionId { get; set; }
        public string targetId { get; set; }
        public List<ReviewTerm> terms { get; set; }
        public string axis { get; set; }
        public string origin { get; set; }
        public string decision { get; set; }
        public ReviewEvaluation evaluation { get; set; }
        public string issue { get; set; }
        public string note { get; set; }
        public string signature { get; set; }
    }
    internal sealed class ReviewRegion
    {
        public string id { get; set; }
        public int pageIndex { get; set; }
        public ReviewBounds bounds { get; set; }
        public string label { get; set; }
    }
    internal sealed class ReviewCorrection
    {
        public string cellId { get; set; }
        public string value { get; set; }
        public string reason { get; set; }
    }
    internal sealed class ReviewRevision
    {
        public int revision { get; set; }
        public string at { get; set; }
        public List<ReviewEquation> equations { get; set; }
        public List<ReviewCorrection> corrections { get; set; }
        public List<ReviewCell> evidence { get; set; }
        public List<int> reviewedPages { get; set; }
    }
    internal sealed class ReviewArchive
    {
        public string scanId { get; set; }
        public string geometryFingerprint { get; set; }
        public int revision { get; set; }
        public List<ReviewCell> evidence { get; set; }
        public List<ReviewRegion> regions { get; set; }
        public List<ReviewEquation> equations { get; set; }
        public List<ReviewCorrection> corrections { get; set; }
        public List<ReviewRevision> history { get; set; }
        public List<int> reviewedPages { get; set; }
    }
    internal sealed class ReviewWorkspace
    {
        public int version { get; set; }
        public string documentId { get; set; }
        public string scanId { get; set; }
        public string geometryFingerprint { get; set; }
        public int pageCount { get; set; }
        public int revision { get; set; }
        public List<ReviewCell> evidence { get; set; }
        public List<ReviewRegion> regions { get; set; }
        public List<ReviewEquation> equations { get; set; }
        public List<ReviewCorrection> corrections { get; set; }
        public List<ReviewRevision> history { get; set; }
        public List<ReviewArchive> archives { get; set; }
        public List<int> reviewedPages { get; set; }
    }
    internal sealed class ReviewDraft
    {
        public string regionId { get; set; }
        public string targetId { get; set; }
        public List<ReviewTerm> terms { get; set; }
        public string axis { get; set; }
    }
    internal sealed class ReviewOperation
    {
        public string kind { get; set; }
        public string equationId { get; set; }
        public ReviewDraft equation { get; set; }
        public List<string> equationIds { get; set; }
        public string decision { get; set; }
        public ReviewCorrection correction { get; set; }
        public ReviewCell cell { get; set; }
        public string issue { get; set; }
        public string note { get; set; }
        public int? revision { get; set; }
        public int? pageIndex { get; set; }
        public bool? reviewed { get; set; }
    }
    internal sealed class ReviewRequest
    {
        public string type { get; set; }
        public int version { get; set; }
        public string requestId { get; set; }
        public string pdfId { get; set; }
        public string mode { get; set; }
        public string scanId { get; set; }
        public int expectedRevision { get; set; }
        public List<ReviewOperation> operations { get; set; }
    }
    internal sealed class ReviewResponse
    {
        public string type { get; set; }
        public int version { get; set; }
        public string requestId { get; set; }
        public string pdfId { get; set; }
        public string status { get; set; }
        public ReviewWorkspace workspace { get; set; }
        public ReviewEvaluation evaluation { get; set; }
        public string error { get; set; }
    }
    internal sealed class ReviewWorkerJob
    {
        public string job_id { get; set; }
        public string command { get; set; }
        public ReviewRequest request { get; set; }
        public string model_base64 { get; set; }
        public string values_base64 { get; set; }
        public string review_base64 { get; set; }
    }
    internal sealed class ReviewWorkerResult
    {
        public string job_id { get; set; }
        public string status { get; set; }
        public ReviewResponse response { get; set; }
        public string review_base64 { get; set; }
    }
}
